### ISSUE TITLE
Can I use if target is my localhost?

### ISSUE THREAD

**Issue by didaquis** [bartveneman/wallace-cli#43]
I tried to use this tool with my localhost in a different ways. This is the result:
```
$ wallace localhost
SyntaxError: Unknown word at line 1, column 1. Source: localhost


wallace http://localhost:80
- Fetching CSS ...
TypeError: this._promise.finally is not a function

$ wallace 127.0.0.1
SyntaxError: Unknown word at line 1, column 1. Source: 127.0.0.1
```
Any of these commands works for me. But the tool seems works with this command: `$ wallace 127.0.0.1:80`. Unfortunately, the results do not seem real.

So... anyone can tell me how I need to use this tool with my localhost?

**Comment by bartveneman** [comment]
Tough one, it uses extract-css.now.sh under the hood, so that will not have access to your localhost. The best I can come up with is to gather all your CSS yourself manually and pipe that into Wallace

Example
```
curl http://localhost/style.css | wallace
```

**Comment by didaquis** [comment]
It works! 

Suggestion: add this information on README.md file

Thanks!
